fragment LineItemProduct on Product {
  databaseId
  name
  slug
  image {
    sourceUrl(size: THUMBNAIL)
    altText
    title
  }
}
fragment LineItemVariation on ProductVariation {
  databaseId
  name
  image {
    sourceUrl(size: THUMBNAIL)
    altText
    title
  }
}
fragment LineItem on LineItem {
  quantity
  total
  id
  product {
    node {
      ...LineItemProduct
    }
  }
  variation {
    node {
      ...LineItemVariation
    }
  }
  calligraphy {
    text
    letters
    notes
    svg
  }
  metaData(
    keysIn: ["_calligraphy_svg", "_calligraphy_text", "_calligraphy_notes", "_calligraphy_settings", "_calligraphy_include_png", "calligraphy_svg", "calligraphy_text", "calligraphy_notes", "calligraphy_settings", "calligraphy_include_png"]
    multiple: true
  ) {
    key
    value
  }
}
